// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegFy.API.GestaoSinistros.Infrastructure.Context;

#nullable disable

namespace SegFy.API.GestaoSinistros.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705140334_CriandoBanco")]
    partial class CriandoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Apolices.Apolice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorSegurado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VigenciaFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VigenciaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("RamoId");

                    b.ToTable("Apolices");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Clientes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Ramos.Ramo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ramos");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Sinistros.HistoricoSinistros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SinistroId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StatusAtual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SinistroId");

                    b.ToTable("HistoricoSinistros");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Sinistros.Sinistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApoliceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorAprovado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceId");

                    b.ToTable("Sinistros");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Apolices.Apolice", b =>
                {
                    b.HasOne("SegFy.API.GestaoSinistros.Domain.Clientes.Cliente", "Cliente")
                        .WithMany("Apolices")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegFy.API.GestaoSinistros.Domain.Ramos.Ramo", "Ramo")
                        .WithMany("Apolices")
                        .HasForeignKey("RamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Ramo");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Sinistros.HistoricoSinistros", b =>
                {
                    b.HasOne("SegFy.API.GestaoSinistros.Domain.Sinistros.Sinistro", "Sinistro")
                        .WithMany("HistoricoSinistros")
                        .HasForeignKey("SinistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinistro");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Sinistros.Sinistro", b =>
                {
                    b.HasOne("SegFy.API.GestaoSinistros.Domain.Apolices.Apolice", "Apolice")
                        .WithMany("Sinistros")
                        .HasForeignKey("ApoliceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apolice");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Apolices.Apolice", b =>
                {
                    b.Navigation("Sinistros");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Clientes.Cliente", b =>
                {
                    b.Navigation("Apolices");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Ramos.Ramo", b =>
                {
                    b.Navigation("Apolices");
                });

            modelBuilder.Entity("SegFy.API.GestaoSinistros.Domain.Sinistros.Sinistro", b =>
                {
                    b.Navigation("HistoricoSinistros");
                });
#pragma warning restore 612, 618
        }
    }
}
